apiVersion: v1
kind: Service
metadata:
  name: vproadd-service
spec:
  ports:
    - port: 80
      targetPort: vproapp-port
      nodePort: 30007 
      protocol: TCP
  selector:
    app: vproapp
  type: NodePort
      